DROP TABLE IF EXISTS teams;
CREATE TABLE teams (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    team TEXT NOT NULL UNIQUE,
    correct INTEGER DEFAULT 0,
    deleted BOOLEAN DEFAULT FALSE
    FOREIGN KEY (favorite_game_category) REFERENCES categories(id)
);